---
title: "R Notebook"
output: html_notebook
---
```{r}
library(gapminder)
library(dplyr)

gapminder

```
Filtering
```{r}
gapminder %>%
  filter(year == 1957)

```
Arrange
```{r}
gapminder %>%
  arrange(lifeExp)

gapminder %>%
  arrange(desc(lifeExp))

```
Filtering and Arranging
```{r}
gapminder %>%
  filter(year==1957) %>%
  arrange(desc(lifeExp))

```
The verb mutate
```{r}
gapminder %>%
  mutate(lifeExp = lifeExp*12)

gapminder %>%
  mutate(lifeExpMonths = lifeExp*12)

```
Combining filter, mutate and arrange
```{r}
gapminder %>%
  filter(year==2007) %>%
  mutate(lifeExpMonths = lifeExp*12) %>%
  arrange(desc(lifeExpMonths))

```
```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point()

```
Log scaling

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```
Colors
```{r}
gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```

