---
title: "R Notebook"
output: html_notebook
---

Intermediate R

```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

-6 * 5 + 2 >= -10 + 1
"raining" <= "table"
TRUE > FALSE

```
Compare Vectors and Matrix
```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin, facebook), nrow=2, byrow=TRUE)

views

views == 14

```
Logigal Operators

```{r}
3 < 4 | 7 < 6
3 < 4 & 4 < 6

linkedin <= 10 & facebook == 13
linkedin <= 10 | facebook == 13
views > 11 & views < 14

```
IF Statement
```{r}
medium <- "Facebook"
num_views <- 14

if (medium == "Linkedin"){
  print ("Showing Linkedin Information ")
} else {
  print ("Unknow medium")
}

if (num_views > 15){
  print ("You're popular!")
} else {
  print ("Try to be more visible!")
}

if (medium == "Linkedin"){
  print ("Showing Linkedin Information ")
} else if (medium == "Facebook"){
  print ("Showing Facebook Information ")
} else {
  print ("Unknow medium")
}

```
ELSEIF 2.0
```{r}

number <- 75
result <- ""

if (number < 10){
  if (number < 5){
   result <- "extra small"
  }
  else {
   result <- "small"
  }
} else if (number < 100){
  result <- "medium"
} else{
  result <- "large"  
}

print(result)

```
LOOPS

```{r}
speed <- 64
while (speed > 30){
  print(paste("Your speed is:", speed))
  speed <- speed - 11
}
speed


speed <- 64
while (speed > 30){
  print(paste("Your speed is:", speed))
  if (speed >= 48){
    print("Slow down big time!")
    speed <- speed - 11
  }
  else{
    print("Slow down!")
    speed <- speed - 6
  }
}
speed


speed <- 88
while (speed > 30){
  print(paste("Your speed is:", speed))
  
  if (speed > 80){
    break
  }

  if (speed >= 48){
    print("Slow down big time!")
    speed <- speed - 11
  }
  else{
    print("Slow down!")
    speed <- speed - 6
  }
}
speed

```
FOR
```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (l in linkedin){
  print(l)
}

for (i in 1:length(linkedin)){
  print(linkedin[i])
}


class(linkedin)

```
FOR OVER A MATRIX
```{r}

views <- matrix(c(linkedin, facebook), nrow=2, byrow=TRUE)
for (row in 1:nrow(views)){
  for (col in 1:ncol(views)){
    print (paste("on row", row, "and column", col, "contains", views[row,col]))
  }
}


```

