---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(gapminder)

gapminder %>%
  summarize(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))

gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))

```
```{r}
gapminder %>%
  group_by(continent) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))

```
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))

```

```{r}
library(ggplot2)
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=medianLifeExp)) +
  geom_point(na.rm = T, color = "red")


```
Grafica de Puntos
```{r}
by_year_cont <- gapminder %>%
  group_by(continent, year) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_year_cont

ggplot(by_year_cont, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_point()

```
Grafica de Lineas
```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=mediangdpPercap)) +
  geom_line()
```
```{r}
by_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_continent

ggplot(by_continent, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_line()

```
Grafica de Barras/Columnnas
```{r}
oceania_1952 <- gapminder %>%
  filter(continent =="Oceania", year == 1952)

oceania_1952

ggplot(oceania_1952, aes(x=country, y=gdpPercap, fill=country)) +
  geom_col()

```
Grafica Histograma
```{r}
library(tidyverse)
library(gapminder)
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952) %>%
  mutate(pop_by_mil = pop/1000000)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop_by_mil)) +
  geom_histogram(bins=50)

ggplot(gapminder_1952, aes(x=pop)) +
  geom_histogram(bins=50) +
  scale_x_log10()

```
Grafica Box plots
```{r}
library(tidyverse)
library(gapminder)
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=continent, y=gdpPercap)) +
  geom_boxplot() +
  scale_y_log10()

```
Data manipulation with dplyr
```{r}
library(tidyverse)

counties <- read_csv ('counties.csv')

counties %>%
  select (state, county, population, men, women) %>%
  mutate(men_proportion=men/population) %>%
  filter (population > 1000) %>%
  arrange(desc(men_proportion))

```
The Count Verb
```{r}
counties_selected <- counties %>%
 select(county, region, state, population, citizens, walk )

counties_selected %>%
  count(region, sort=TRUE)

counties_selected %>%
  count(state, wt = citizens) %>%
  arrange(desc(n))

counties_selected %>%
  mutate(population_walk = population*walk/100 ) %>%
  count(state, wt=population_walk, sort=TRUE)

```
Summarizing
```{r}
counties_selected <- counties %>%
 select(county, population, income, unemployment)

counties_selected %>%
  summarize(min_population=min(population), max_unemployment=max(unemployment), avg_income = mean(income))


counties_selected <- counties %>%
 select(state, county, population, land_area)

counties_selected %>%
  group_by(state) %>%
  summarize(total_area=sum(land_area), total_population=sum(population))

counties_selected <- counties %>%
 select(region, state, county, population)

counties_selected %>%
  group_by(region, state) %>%
  summarize(total_pop=sum(population)) %>%
  summarize(avg_pop=mean(total_pop), med_pop=median(total_pop))

counties_selected %>%
  group_by(region, state) %>%
  summarize(total_pop=sum(population)) %>%
  ungroup() %>%
  summarize(avg_pop=mean(total_pop), med_pop=median(total_pop))
```
The top_n verd
```{r}
counties_selected <- counties %>%
 select(region, state, county, metro, population, walk)

counties_selected %>%
  group_by(region) %>%
  top_n(2, walk)

counties_selected <- counties %>%
 select(region, state, county, population, income)

counties_selected %>%
  group_by(region, state) %>%
  summarize (avg_income=mean(income)) %>%
  #ungroup() %>%
  top_n(1, avg_income)

```
```{r}
counties_selected <- counties %>%
 select(state, metro, population)

counties_selected %>%
  group_by(state, metro) %>%
  summarize(total_pop = sum(population))




```
```{r}
counties_selected <- counties %>%
 select(state, metro, population)

counties_selected %>%
  group_by(state, metro) %>%
  summarize(total_pop = sum(population)) %>%
  top_n(1, total_pop) %>%
  ungroup() %>%
  count(metro, wt=total_pop)


```
