---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)

inventories <- read_csv('inventories.csv')
inventory_parts <- read_csv('inventory_parts.csv')
colors <- read_csv('colors.csv')

inventories
inventory_parts
colors

```

```{r}
inventory_parts_join <- inventories %>%
  inner_join (inventory_parts, by=c("id" = "inventory_id")) %>%
  select (-id, -version) %>%
  arrange(desc(quantity))

batmobile <- inventory_parts_join %>%
  filter(set_num == "7784-1") %>%
  select(-set_num)

batwing <- inventory_parts_join %>%
  filter(set_num == "70916-1") %>%
  select(-set_num)

batmobile %>%
  inner_join(batwing, c("part_num", "color_id"), suffix=c("_batmobile","_batwing"))


```
```{r}
parts %>%
  inner_join(inventory_parts, by="part_num")

inventory_parts %>%
  inner_join(parts, by="part_num")
```
Joining three or more tables
```{r}
sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by=c("color_id" = "id"), suffix=c("_sets", "_colors")) %>%
  count(name_colors) %>%
  arrange(desc(n))

```


