---
title: "R Notebook"
output: html_notebook
---

Aritmetica en R
```{r}
6+10 #Suma
5-1  #Resta
5*2 #Multiplicacion
(5-2)/2 #Division
2^5 #Exponente
28%%6 #Modulo o residuo
```
Asignacion de Variables
```{r}
x = 15
y = 10
total = x+y
total
```
Clase / Tipos de Dato
```{r}
mycaracter = 'armando'
myboleano = 'TRUE'
mycaracter
myboleano
```
```{r}
class(mycaracter)
class(myboleano)
```
Uso de Vectores
```{r}
vectornumerico <- c(1, 2, 3, 4, 5)
vectornumerico
vectorboleano <- c(TRUE,FALSE,TRUE)
vectorboleano
vectorcaracter <- c("Jorge", "Armando", "Rodriguez")
vectorcaracter
```
Nombrando Vectores
```{r}
vectortabla = c("Jorge", "Rodriguez")
names(vectortabla) = c("Nombre", "Apellido")
vectortabla
```
Comparando y seleccionando
```{r}
Age = 17
Age >= 18
```
```{r}
VectorA = c(1,2,3)
VectorB = c(4,5,6)
VectorTotal = VectorA + VectorB
VectorTotal
totalvector = sum(VectorTotal)
totalvector
```
```{r}
VectorTotal[1]
VectorTotal[c(2,3)]
```
```{r}
Var1 = 5
Var2 = 10
Var3 = 15
Var4 = 20
Var5 = 25

Vector = c(Var1,Var2,Var3, Var4, Var5)
Vector
total = sum(Vector)
total
Vector[2:4]
mean(Vector)
selectionvector = Vector > 10
selectionvector

otrovector = Vector[selectionvector]


```
Matrices
```{r}
matrix(1:9, byrow=TRUE,nrow=3)

```
```{r}
matrix(1:9, byrow=FALSE,nrow=3)
```
```{r}
new_hope <- c(460.998, 314.4)
empire_strike <- c(2980.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi)
box_office

star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
star_wars_matrix

region <- c("US", "LATAM")
titles <- c("A new Hope", "The Empire Strikes Back", "Return of the Jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles

star_wars_matrix

worldwide_vector <- rowSums(star_wars_matrix)
all_wars_variable <- cbind(star_wars_matrix, worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(all_wars_variable)
worldwide_cols

all_wars_variable <- rbind(all_wars_variable, worldwide_cols)
all_wars_variable

LATAM_all <- all_wars_variable[,2]
LATAM_all

US_all <- all_wars_variable[,1]
US_all

mean(LATAM_all)

US_all <- all_wars_variable[1:3,1] * 1
US_all
```
Factores
```{r}
sex_vector <- c("Male", "Female", "Male", "Male", "Female")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

temperature_vector <- c("High", "Low", "High", "Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High"))
factor_temperature_vector

```
Factor Levels
```{r}
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector

levels(factor_survey_vector) <- c("Female", "Male")
factor_survey_vector

```
Summarizing a Factor (resumen/caracteristicas)
```{r}
summary(survey_vector)
summary(factor_survey_vector)

male <- factor_survey_vector[1]
female <- factor_survey_vector[2]
male
female

speed_vector <- c("medium", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels=c("slow","medium","fast"))
factor_speed_vector

da2 <- factor_speed_vector[2]
da3 <- factor_speed_vector[1]

da2
da3

da2 < da3


```
